/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegos.edvin_reyes;

import inserLet.insertar;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class serpientes extends javax.swing.JFrame {

    /**
     * Creates new form serpientes
     */
    public serpientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[][] rellenar = {{"1", "2", "3", "4", "5"}, {"","6", "7", "8", "9", "10"}, {"","11", "12", "13", "14", "15"},
        {"","16", "17", "18", "19", "20"}, {"","21", "22", "23", "24", "25"}};
        JPanel[] panel = {numerosEn, numerosEn1, numerosEn2, numerosEn3, numerosEn4};
        JLabel[] boton = {jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17,
             jLabel18, jLabel19, jLabel20, jLabel21, jLabel22, jLabel23, jLabel24, jLabel25, jLabel26, jLabel27, jLabel28};
        for (int i = 0; i < 5; i++) {
            new insertar(rellenar[i][0],
                    rellenar[i][1],
                    rellenar[i][2],
                    rellenar[i][3],
                    rellenar[i][4]).escritor(boton[i], panel[i].getComponents());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serPanel = new javax.swing.JPanel();
        arribaPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        centroPanel = new javax.swing.JPanel();
        numerosPanel = new javax.swing.JPanel();
        numerosEn4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        numerosPanel1 = new javax.swing.JPanel();
        numerosEn3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        numerosPanel2 = new javax.swing.JPanel();
        numerosEn2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        numerosPanel3 = new javax.swing.JPanel();
        numerosEn1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        numerosPanel4 = new javax.swing.JPanel();
        numerosEn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        abajoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(760, 852));

        serPanel.setLayout(new java.awt.BorderLayout());

        arribaPanel.setPreferredSize(new java.awt.Dimension(760, 80));
        arribaPanel.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Serpientes y escaleras");
        jPanel7.add(jLabel1, java.awt.BorderLayout.CENTER);

        arribaPanel.add(jPanel7, java.awt.BorderLayout.CENTER);

        serPanel.add(arribaPanel, java.awt.BorderLayout.PAGE_START);

        centroPanel.setPreferredSize(new java.awt.Dimension(286, 552));
        centroPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 23));

        numerosPanel.setLayout(new java.awt.GridLayout(1, 3, 23, 2));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("jLabel24");
        jLabel24.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn4.add(jLabel24);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("jLabel25");
        jLabel25.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn4.add(jLabel25);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("jLabel26");
        jLabel26.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn4.add(jLabel26);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("jLabel27");
        jLabel27.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn4.add(jLabel27);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("jLabel28");
        jLabel28.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn4.add(jLabel28);

        numerosPanel.add(numerosEn4);

        centroPanel.add(numerosPanel);

        numerosPanel1.setLayout(new java.awt.GridLayout(1, 0, 23, 0));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("jLabel19");
        jLabel19.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn3.add(jLabel19);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("jLabel20");
        jLabel20.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn3.add(jLabel20);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("jLabel21");
        jLabel21.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn3.add(jLabel21);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("jLabel22");
        jLabel22.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn3.add(jLabel22);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("jLabel23");
        jLabel23.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn3.add(jLabel23);

        numerosPanel1.add(numerosEn3);

        centroPanel.add(numerosPanel1);

        numerosPanel2.setLayout(new java.awt.GridLayout(1, 0, 23, 0));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("jLabel14");
        jLabel14.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn2.add(jLabel14);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("jLabel15");
        jLabel15.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn2.add(jLabel15);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("jLabel16");
        jLabel16.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn2.add(jLabel16);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("jLabel17");
        jLabel17.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn2.add(jLabel17);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("jLabel18");
        jLabel18.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn2.add(jLabel18);

        numerosPanel2.add(numerosEn2);

        centroPanel.add(numerosPanel2);

        numerosPanel3.setLayout(new java.awt.GridLayout(1, 0, 23, 0));

        numerosEn1.setPreferredSize(new java.awt.Dimension(125, 125));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("jLabel9");
        jLabel9.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn1.add(jLabel9);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("jLabel10");
        jLabel10.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn1.add(jLabel10);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("jLabel11");
        jLabel11.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn1.add(jLabel11);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("jLabel12");
        jLabel12.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn1.add(jLabel12);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("jLabel13");
        jLabel13.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn1.add(jLabel13);

        numerosPanel3.add(numerosEn1);

        centroPanel.add(numerosPanel3);

        numerosPanel4.setLayout(new java.awt.GridLayout());

        numerosEn.setPreferredSize(new java.awt.Dimension(47, 25));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel5");
        jLabel5.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");
        jLabel6.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("jLabel7");
        jLabel7.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");
        jLabel8.setPreferredSize(new java.awt.Dimension(125, 110));
        numerosEn.add(jLabel8);

        numerosPanel4.add(numerosEn);

        centroPanel.add(numerosPanel4);

        serPanel.add(centroPanel, java.awt.BorderLayout.CENTER);

        abajoPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        abajoPanel.setPreferredSize(new java.awt.Dimension(760, 80));
        abajoPanel.setRequestFocusEnabled(false);
        abajoPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(651, 100));
        jLabel2.setRequestFocusEnabled(false);
        abajoPanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(180, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, java.awt.BorderLayout.CENTER);

        abajoPanel.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jButton26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton26.setText("Tirar Dados");
        jButton26.setToolTipText("");
        jButton26.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton26MouseClicked(evt);
            }
        });
        abajoPanel.add(jButton26, java.awt.BorderLayout.LINE_START);

        serPanel.add(abajoPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(serPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseClicked
        int valor = 0;
        int numero = (int) (Math.random() * 5 + 1);

        jLabel3.setText("numero" + Integer.toString(numero));
        
        if (valor >= 25 ) {
            JOptionPane.showMessageDialog(this, "Gandador");
        }else{
            switch(valor){
                case 1:
                    jLabel4.setBackground(Color.red);
                    break;
            }
        }
        
    }//GEN-LAST:event_jButton26MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serpientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serpientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serpientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serpientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serpientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abajoPanel;
    private javax.swing.JPanel arribaPanel;
    private javax.swing.JPanel centroPanel;
    private javax.swing.JButton jButton26;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel numerosEn;
    private javax.swing.JPanel numerosEn1;
    private javax.swing.JPanel numerosEn2;
    private javax.swing.JPanel numerosEn3;
    private javax.swing.JPanel numerosEn4;
    private javax.swing.JPanel numerosPanel;
    private javax.swing.JPanel numerosPanel1;
    private javax.swing.JPanel numerosPanel2;
    private javax.swing.JPanel numerosPanel3;
    private javax.swing.JPanel numerosPanel4;
    private javax.swing.JPanel serPanel;
    // End of variables declaration//GEN-END:variables

}
